/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_stevej_android_facedetection_OpenCV */

#ifndef _Included_org_stevej_android_facedetection_utils_ImageUtils
#define _Included_org_stevej_android_facedetection_utils_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif

	extern void in_range_neon(uint8_t*, uint8_t*, jint, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t);
	extern void extract_hsv_neon(uint8_t *, uint8_t *, uint8_t *, uint8_t *, jint);
	JNIEXPORT void JNICALL Java_org_stevej_android_facedetection_utils_ImageUtils_init(JNIEnv *, jclass, jint, jint);
	JNIEXPORT void JNICALL Java_org_stevej_android_facedetection_utils_ImageUtils_deinit(JNIEnv *, jclass);

	JNIEXPORT void JNICALL Java_org_stevej_android_facedetection_utils_ImageUtils_findMarker(JNIEnv *, jclass, jbyteArray, jint, jint, jintArray,jboolean);
	JNIEXPORT void JNICALL Java_org_stevej_android_facedetection_utils_ImageUtils_RGBAToYUV(JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

	JNIEXPORT void JNICALL Java_org_stevej_android_imageprocessing_utils_ImageUtils_GtoAGGG(JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);
#ifdef __cplusplus
}
#endif
#endif

